// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: BizContactAddNotice.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class BizContactAddNotice {
  private BizContactAddNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BizContactAddNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.BizContactAddNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 商家所属微信号
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    java.lang.String getWeChatId();
    /**
     * <pre>
     * 商家所属微信号
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    com.google.protobuf.ByteString
        getWeChatIdBytes();

    /**
     * <pre>
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
     */
    boolean hasContact();
    /**
     * <pre>
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage getContact();
    /**
     * <pre>
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessageOrBuilder getContactOrBuilder();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.BizContactAddNoticeMessage}
   */
  public  static final class BizContactAddNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.BizContactAddNoticeMessage)
      BizContactAddNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BizContactAddNoticeMessage.newBuilder() to construct.
    private BizContactAddNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BizContactAddNoticeMessage() {
      weChatId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BizContactAddNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              weChatId_ = s;
              break;
            }
            case 18: {
              Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.Builder subBuilder = null;
              if (contact_ != null) {
                subBuilder = contact_.toBuilder();
              }
              contact_ = input.readMessage(Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(contact_);
                contact_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage.Builder.class);
    }

    public static final int WECHATID_FIELD_NUMBER = 1;
    private volatile java.lang.Object weChatId_;
    /**
     * <pre>
     * 商家所属微信号
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public java.lang.String getWeChatId() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weChatId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 商家所属微信号
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatIdBytes() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weChatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTACT_FIELD_NUMBER = 2;
    private Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage contact_;
    /**
     * <pre>
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
     */
    public boolean hasContact() {
      return contact_ != null;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage getContact() {
      return contact_ == null ? Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.getDefaultInstance() : contact_;
    }
    /**
     * <pre>
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessageOrBuilder getContactOrBuilder() {
      return getContact();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWeChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, weChatId_);
      }
      if (contact_ != null) {
        output.writeMessage(2, getContact());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWeChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, weChatId_);
      }
      if (contact_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getContact());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage other = (Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage) obj;

      boolean result = true;
      result = result && getWeChatId()
          .equals(other.getWeChatId());
      result = result && (hasContact() == other.hasContact());
      if (hasContact()) {
        result = result && getContact()
            .equals(other.getContact());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WECHATID_FIELD_NUMBER;
      hash = (53 * hash) + getWeChatId().hashCode();
      if (hasContact()) {
        hash = (37 * hash) + CONTACT_FIELD_NUMBER;
        hash = (53 * hash) + getContact().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.BizContactAddNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.BizContactAddNoticeMessage)
        Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        weChatId_ = "";

        if (contactBuilder_ == null) {
          contact_ = null;
        } else {
          contact_ = null;
          contactBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage result = new Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage(this);
        result.weChatId_ = weChatId_;
        if (contactBuilder_ == null) {
          result.contact_ = contact_;
        } else {
          result.contact_ = contactBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage.getDefaultInstance()) return this;
        if (!other.getWeChatId().isEmpty()) {
          weChatId_ = other.weChatId_;
          onChanged();
        }
        if (other.hasContact()) {
          mergeContact(other.getContact());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object weChatId_ = "";
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public java.lang.String getWeChatId() {
        java.lang.Object ref = weChatId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weChatId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatIdBytes() {
        java.lang.Object ref = weChatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weChatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder clearWeChatId() {
        
        weChatId_ = getDefaultInstance().getWeChatId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weChatId_ = value;
        onChanged();
        return this;
      }

      private Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage contact_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage, Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessageOrBuilder> contactBuilder_;
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      public boolean hasContact() {
        return contactBuilder_ != null || contact_ != null;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage getContact() {
        if (contactBuilder_ == null) {
          return contact_ == null ? Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.getDefaultInstance() : contact_;
        } else {
          return contactBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      public Builder setContact(Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage value) {
        if (contactBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          contact_ = value;
          onChanged();
        } else {
          contactBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      public Builder setContact(
          Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.Builder builderForValue) {
        if (contactBuilder_ == null) {
          contact_ = builderForValue.build();
          onChanged();
        } else {
          contactBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      public Builder mergeContact(Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage value) {
        if (contactBuilder_ == null) {
          if (contact_ != null) {
            contact_ =
              Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.newBuilder(contact_).mergeFrom(value).buildPartial();
          } else {
            contact_ = value;
          }
          onChanged();
        } else {
          contactBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      public Builder clearContact() {
        if (contactBuilder_ == null) {
          contact_ = null;
          onChanged();
        } else {
          contact_ = null;
          contactBuilder_ = null;
        }

        return this;
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.Builder getContactBuilder() {
        
        onChanged();
        return getContactFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessageOrBuilder getContactOrBuilder() {
        if (contactBuilder_ != null) {
          return contactBuilder_.getMessageOrBuilder();
        } else {
          return contact_ == null ?
              Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.getDefaultInstance() : contact_;
        }
      }
      /**
       * <pre>
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.BizContactMessage Contact = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage, Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessageOrBuilder> 
          getContactFieldBuilder() {
        if (contactBuilder_ == null) {
          contactBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage, Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.BizContactMessageOrBuilder>(
                  getContact(),
                  getParentForChildren(),
                  isClean());
          contact_ = null;
        }
        return contactBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.BizContactAddNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.BizContactAddNoticeMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BizContactAddNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<BizContactAddNoticeMessage>() {
      public BizContactAddNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BizContactAddNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BizContactAddNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BizContactAddNoticeMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.BizContactAddNotice.BizContactAddNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031BizContactAddNotice.proto\022\027Jubo.JuLiao" +
      ".IM.Wx.Proto\032\032BizContactPushNotice.proto" +
      "\"k\n\032BizContactAddNoticeMessage\022\020\n\010WeChat" +
      "Id\030\001 \001(\t\022;\n\007Contact\030\002 \001(\0132*.Jubo.JuLiao." +
      "IM.Wx.Proto.BizContactMessageb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.getDescriptor(),
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_BizContactAddNoticeMessage_descriptor,
        new java.lang.String[] { "WeChatId", "Contact", });
    Jubo.JuLiao.IM.Wx.Proto.BizContactPushNotice.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
