// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ConversationPushNotice.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class ConversationPushNotice {
  private ConversationPushNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConversMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.ConversMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 好友微信内部全局唯一识别码
     * </pre>
     *
     * <code>string UserName = 1;</code>
     */
    java.lang.String getUserName();
    /**
     * <pre>
     * 好友微信内部全局唯一识别码
     * </pre>
     *
     * <code>string UserName = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     * 消息概要显示
     * </pre>
     *
     * <code>string Digest = 2;</code>
     */
    java.lang.String getDigest();
    /**
     * <pre>
     * 消息概要显示
     * </pre>
     *
     * <code>string Digest = 2;</code>
     */
    com.google.protobuf.ByteString
        getDigestBytes();

    /**
     * <pre>
     * 消息发送者id
     * </pre>
     *
     * <code>string DigestUser = 3;</code>
     */
    java.lang.String getDigestUser();
    /**
     * <pre>
     * 消息发送者id
     * </pre>
     *
     * <code>string DigestUser = 3;</code>
     */
    com.google.protobuf.ByteString
        getDigestUserBytes();

    /**
     * <pre>
     * 最后消息是否自己发送
     * </pre>
     *
     * <code>bool IsSend = 4;</code>
     */
    boolean getIsSend();

    /**
     * <pre>
     * 消息条数
     * </pre>
     *
     * <code>int32 MsgCnt = 5;</code>
     */
    int getMsgCnt();

    /**
     * <pre>
     * 未读消息条数
     * </pre>
     *
     * <code>int32 UnreadCnt = 6;</code>
     */
    int getUnreadCnt();

    /**
     * <pre>
     * 最后消息的时间
     * </pre>
     *
     * <code>int64 UpdateTime = 7;</code>
     */
    long getUpdateTime();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.ConversMessage}
   */
  public  static final class ConversMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.ConversMessage)
      ConversMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConversMessage.newBuilder() to construct.
    private ConversMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConversMessage() {
      userName_ = "";
      digest_ = "";
      digestUser_ = "";
      isSend_ = false;
      msgCnt_ = 0;
      unreadCnt_ = 0;
      updateTime_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConversMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              digest_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              digestUser_ = s;
              break;
            }
            case 32: {

              isSend_ = input.readBool();
              break;
            }
            case 40: {

              msgCnt_ = input.readInt32();
              break;
            }
            case 48: {

              unreadCnt_ = input.readInt32();
              break;
            }
            case 56: {

              updateTime_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.class, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder.class);
    }

    public static final int USERNAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     * 好友微信内部全局唯一识别码
     * </pre>
     *
     * <code>string UserName = 1;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 好友微信内部全局唯一识别码
     * </pre>
     *
     * <code>string UserName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIGEST_FIELD_NUMBER = 2;
    private volatile java.lang.Object digest_;
    /**
     * <pre>
     * 消息概要显示
     * </pre>
     *
     * <code>string Digest = 2;</code>
     */
    public java.lang.String getDigest() {
      java.lang.Object ref = digest_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        digest_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息概要显示
     * </pre>
     *
     * <code>string Digest = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDigestBytes() {
      java.lang.Object ref = digest_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digest_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DIGESTUSER_FIELD_NUMBER = 3;
    private volatile java.lang.Object digestUser_;
    /**
     * <pre>
     * 消息发送者id
     * </pre>
     *
     * <code>string DigestUser = 3;</code>
     */
    public java.lang.String getDigestUser() {
      java.lang.Object ref = digestUser_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        digestUser_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 消息发送者id
     * </pre>
     *
     * <code>string DigestUser = 3;</code>
     */
    public com.google.protobuf.ByteString
        getDigestUserBytes() {
      java.lang.Object ref = digestUser_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        digestUser_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISSEND_FIELD_NUMBER = 4;
    private boolean isSend_;
    /**
     * <pre>
     * 最后消息是否自己发送
     * </pre>
     *
     * <code>bool IsSend = 4;</code>
     */
    public boolean getIsSend() {
      return isSend_;
    }

    public static final int MSGCNT_FIELD_NUMBER = 5;
    private int msgCnt_;
    /**
     * <pre>
     * 消息条数
     * </pre>
     *
     * <code>int32 MsgCnt = 5;</code>
     */
    public int getMsgCnt() {
      return msgCnt_;
    }

    public static final int UNREADCNT_FIELD_NUMBER = 6;
    private int unreadCnt_;
    /**
     * <pre>
     * 未读消息条数
     * </pre>
     *
     * <code>int32 UnreadCnt = 6;</code>
     */
    public int getUnreadCnt() {
      return unreadCnt_;
    }

    public static final int UPDATETIME_FIELD_NUMBER = 7;
    private long updateTime_;
    /**
     * <pre>
     * 最后消息的时间
     * </pre>
     *
     * <code>int64 UpdateTime = 7;</code>
     */
    public long getUpdateTime() {
      return updateTime_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userName_);
      }
      if (!getDigestBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, digest_);
      }
      if (!getDigestUserBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, digestUser_);
      }
      if (isSend_ != false) {
        output.writeBool(4, isSend_);
      }
      if (msgCnt_ != 0) {
        output.writeInt32(5, msgCnt_);
      }
      if (unreadCnt_ != 0) {
        output.writeInt32(6, unreadCnt_);
      }
      if (updateTime_ != 0L) {
        output.writeInt64(7, updateTime_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userName_);
      }
      if (!getDigestBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, digest_);
      }
      if (!getDigestUserBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, digestUser_);
      }
      if (isSend_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isSend_);
      }
      if (msgCnt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, msgCnt_);
      }
      if (unreadCnt_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, unreadCnt_);
      }
      if (updateTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, updateTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage other = (Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage) obj;

      boolean result = true;
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getDigest()
          .equals(other.getDigest());
      result = result && getDigestUser()
          .equals(other.getDigestUser());
      result = result && (getIsSend()
          == other.getIsSend());
      result = result && (getMsgCnt()
          == other.getMsgCnt());
      result = result && (getUnreadCnt()
          == other.getUnreadCnt());
      result = result && (getUpdateTime()
          == other.getUpdateTime());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + DIGEST_FIELD_NUMBER;
      hash = (53 * hash) + getDigest().hashCode();
      hash = (37 * hash) + DIGESTUSER_FIELD_NUMBER;
      hash = (53 * hash) + getDigestUser().hashCode();
      hash = (37 * hash) + ISSEND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsSend());
      hash = (37 * hash) + MSGCNT_FIELD_NUMBER;
      hash = (53 * hash) + getMsgCnt();
      hash = (37 * hash) + UNREADCNT_FIELD_NUMBER;
      hash = (53 * hash) + getUnreadCnt();
      hash = (37 * hash) + UPDATETIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getUpdateTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.ConversMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.ConversMessage)
        Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.class, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userName_ = "";

        digest_ = "";

        digestUser_ = "";

        isSend_ = false;

        msgCnt_ = 0;

        unreadCnt_ = 0;

        updateTime_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage result = new Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage(this);
        result.userName_ = userName_;
        result.digest_ = digest_;
        result.digestUser_ = digestUser_;
        result.isSend_ = isSend_;
        result.msgCnt_ = msgCnt_;
        result.unreadCnt_ = unreadCnt_;
        result.updateTime_ = updateTime_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.getDefaultInstance()) return this;
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getDigest().isEmpty()) {
          digest_ = other.digest_;
          onChanged();
        }
        if (!other.getDigestUser().isEmpty()) {
          digestUser_ = other.digestUser_;
          onChanged();
        }
        if (other.getIsSend() != false) {
          setIsSend(other.getIsSend());
        }
        if (other.getMsgCnt() != 0) {
          setMsgCnt(other.getMsgCnt());
        }
        if (other.getUnreadCnt() != 0) {
          setUnreadCnt(other.getUnreadCnt());
        }
        if (other.getUpdateTime() != 0L) {
          setUpdateTime(other.getUpdateTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string UserName = 1;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string UserName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string UserName = 1;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string UserName = 1;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 好友微信内部全局唯一识别码
       * </pre>
       *
       * <code>string UserName = 1;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object digest_ = "";
      /**
       * <pre>
       * 消息概要显示
       * </pre>
       *
       * <code>string Digest = 2;</code>
       */
      public java.lang.String getDigest() {
        java.lang.Object ref = digest_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          digest_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息概要显示
       * </pre>
       *
       * <code>string Digest = 2;</code>
       */
      public com.google.protobuf.ByteString
          getDigestBytes() {
        java.lang.Object ref = digest_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          digest_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息概要显示
       * </pre>
       *
       * <code>string Digest = 2;</code>
       */
      public Builder setDigest(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        digest_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息概要显示
       * </pre>
       *
       * <code>string Digest = 2;</code>
       */
      public Builder clearDigest() {
        
        digest_ = getDefaultInstance().getDigest();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息概要显示
       * </pre>
       *
       * <code>string Digest = 2;</code>
       */
      public Builder setDigestBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        digest_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object digestUser_ = "";
      /**
       * <pre>
       * 消息发送者id
       * </pre>
       *
       * <code>string DigestUser = 3;</code>
       */
      public java.lang.String getDigestUser() {
        java.lang.Object ref = digestUser_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          digestUser_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 消息发送者id
       * </pre>
       *
       * <code>string DigestUser = 3;</code>
       */
      public com.google.protobuf.ByteString
          getDigestUserBytes() {
        java.lang.Object ref = digestUser_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          digestUser_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 消息发送者id
       * </pre>
       *
       * <code>string DigestUser = 3;</code>
       */
      public Builder setDigestUser(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        digestUser_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息发送者id
       * </pre>
       *
       * <code>string DigestUser = 3;</code>
       */
      public Builder clearDigestUser() {
        
        digestUser_ = getDefaultInstance().getDigestUser();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息发送者id
       * </pre>
       *
       * <code>string DigestUser = 3;</code>
       */
      public Builder setDigestUserBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        digestUser_ = value;
        onChanged();
        return this;
      }

      private boolean isSend_ ;
      /**
       * <pre>
       * 最后消息是否自己发送
       * </pre>
       *
       * <code>bool IsSend = 4;</code>
       */
      public boolean getIsSend() {
        return isSend_;
      }
      /**
       * <pre>
       * 最后消息是否自己发送
       * </pre>
       *
       * <code>bool IsSend = 4;</code>
       */
      public Builder setIsSend(boolean value) {
        
        isSend_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 最后消息是否自己发送
       * </pre>
       *
       * <code>bool IsSend = 4;</code>
       */
      public Builder clearIsSend() {
        
        isSend_ = false;
        onChanged();
        return this;
      }

      private int msgCnt_ ;
      /**
       * <pre>
       * 消息条数
       * </pre>
       *
       * <code>int32 MsgCnt = 5;</code>
       */
      public int getMsgCnt() {
        return msgCnt_;
      }
      /**
       * <pre>
       * 消息条数
       * </pre>
       *
       * <code>int32 MsgCnt = 5;</code>
       */
      public Builder setMsgCnt(int value) {
        
        msgCnt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 消息条数
       * </pre>
       *
       * <code>int32 MsgCnt = 5;</code>
       */
      public Builder clearMsgCnt() {
        
        msgCnt_ = 0;
        onChanged();
        return this;
      }

      private int unreadCnt_ ;
      /**
       * <pre>
       * 未读消息条数
       * </pre>
       *
       * <code>int32 UnreadCnt = 6;</code>
       */
      public int getUnreadCnt() {
        return unreadCnt_;
      }
      /**
       * <pre>
       * 未读消息条数
       * </pre>
       *
       * <code>int32 UnreadCnt = 6;</code>
       */
      public Builder setUnreadCnt(int value) {
        
        unreadCnt_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 未读消息条数
       * </pre>
       *
       * <code>int32 UnreadCnt = 6;</code>
       */
      public Builder clearUnreadCnt() {
        
        unreadCnt_ = 0;
        onChanged();
        return this;
      }

      private long updateTime_ ;
      /**
       * <pre>
       * 最后消息的时间
       * </pre>
       *
       * <code>int64 UpdateTime = 7;</code>
       */
      public long getUpdateTime() {
        return updateTime_;
      }
      /**
       * <pre>
       * 最后消息的时间
       * </pre>
       *
       * <code>int64 UpdateTime = 7;</code>
       */
      public Builder setUpdateTime(long value) {
        
        updateTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 最后消息的时间
       * </pre>
       *
       * <code>int64 UpdateTime = 7;</code>
       */
      public Builder clearUpdateTime() {
        
        updateTime_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.ConversMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.ConversMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConversMessage>
        PARSER = new com.google.protobuf.AbstractParser<ConversMessage>() {
      public ConversMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConversMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConversMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConversMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ConversationPushNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.ConversationPushNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    java.lang.String getWeChatId();
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    com.google.protobuf.ByteString
        getWeChatIdBytes();

    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    java.util.List<Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage> 
        getConversList();
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage getConvers(int index);
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    int getConversCount();
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder> 
        getConversOrBuilderList();
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder getConversOrBuilder(
        int index);

    /**
     * <code>int32 Size = 3;</code>
     */
    int getSize();

    /**
     * <code>int32 Count = 4;</code>
     */
    int getCount();

    /**
     * <code>int32 Page = 5;</code>
     */
    int getPage();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.ConversationPushNoticeMessage}
   */
  public  static final class ConversationPushNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.ConversationPushNoticeMessage)
      ConversationPushNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ConversationPushNoticeMessage.newBuilder() to construct.
    private ConversationPushNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ConversationPushNoticeMessage() {
      weChatId_ = "";
      convers_ = java.util.Collections.emptyList();
      size_ = 0;
      count_ = 0;
      page_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ConversationPushNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              weChatId_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                convers_ = new java.util.ArrayList<Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage>();
                mutable_bitField0_ |= 0x00000002;
              }
              convers_.add(
                  input.readMessage(Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.parser(), extensionRegistry));
              break;
            }
            case 24: {

              size_ = input.readInt32();
              break;
            }
            case 32: {

              count_ = input.readInt32();
              break;
            }
            case 40: {

              page_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          convers_ = java.util.Collections.unmodifiableList(convers_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage.Builder.class);
    }

    private int bitField0_;
    public static final int WECHATID_FIELD_NUMBER = 1;
    private volatile java.lang.Object weChatId_;
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public java.lang.String getWeChatId() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weChatId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatIdBytes() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weChatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONVERS_FIELD_NUMBER = 2;
    private java.util.List<Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage> convers_;
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    public java.util.List<Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage> getConversList() {
      return convers_;
    }
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    public java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder> 
        getConversOrBuilderList() {
      return convers_;
    }
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    public int getConversCount() {
      return convers_.size();
    }
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage getConvers(int index) {
      return convers_.get(index);
    }
    /**
     * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder getConversOrBuilder(
        int index) {
      return convers_.get(index);
    }

    public static final int SIZE_FIELD_NUMBER = 3;
    private int size_;
    /**
     * <code>int32 Size = 3;</code>
     */
    public int getSize() {
      return size_;
    }

    public static final int COUNT_FIELD_NUMBER = 4;
    private int count_;
    /**
     * <code>int32 Count = 4;</code>
     */
    public int getCount() {
      return count_;
    }

    public static final int PAGE_FIELD_NUMBER = 5;
    private int page_;
    /**
     * <code>int32 Page = 5;</code>
     */
    public int getPage() {
      return page_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWeChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, weChatId_);
      }
      for (int i = 0; i < convers_.size(); i++) {
        output.writeMessage(2, convers_.get(i));
      }
      if (size_ != 0) {
        output.writeInt32(3, size_);
      }
      if (count_ != 0) {
        output.writeInt32(4, count_);
      }
      if (page_ != 0) {
        output.writeInt32(5, page_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWeChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, weChatId_);
      }
      for (int i = 0; i < convers_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, convers_.get(i));
      }
      if (size_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, size_);
      }
      if (count_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, count_);
      }
      if (page_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, page_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage other = (Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage) obj;

      boolean result = true;
      result = result && getWeChatId()
          .equals(other.getWeChatId());
      result = result && getConversList()
          .equals(other.getConversList());
      result = result && (getSize()
          == other.getSize());
      result = result && (getCount()
          == other.getCount());
      result = result && (getPage()
          == other.getPage());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WECHATID_FIELD_NUMBER;
      hash = (53 * hash) + getWeChatId().hashCode();
      if (getConversCount() > 0) {
        hash = (37 * hash) + CONVERS_FIELD_NUMBER;
        hash = (53 * hash) + getConversList().hashCode();
      }
      hash = (37 * hash) + SIZE_FIELD_NUMBER;
      hash = (53 * hash) + getSize();
      hash = (37 * hash) + COUNT_FIELD_NUMBER;
      hash = (53 * hash) + getCount();
      hash = (37 * hash) + PAGE_FIELD_NUMBER;
      hash = (53 * hash) + getPage();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.ConversationPushNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.ConversationPushNoticeMessage)
        Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getConversFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        weChatId_ = "";

        if (conversBuilder_ == null) {
          convers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          conversBuilder_.clear();
        }
        size_ = 0;

        count_ = 0;

        page_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage result = new Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.weChatId_ = weChatId_;
        if (conversBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            convers_ = java.util.Collections.unmodifiableList(convers_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.convers_ = convers_;
        } else {
          result.convers_ = conversBuilder_.build();
        }
        result.size_ = size_;
        result.count_ = count_;
        result.page_ = page_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage.getDefaultInstance()) return this;
        if (!other.getWeChatId().isEmpty()) {
          weChatId_ = other.weChatId_;
          onChanged();
        }
        if (conversBuilder_ == null) {
          if (!other.convers_.isEmpty()) {
            if (convers_.isEmpty()) {
              convers_ = other.convers_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureConversIsMutable();
              convers_.addAll(other.convers_);
            }
            onChanged();
          }
        } else {
          if (!other.convers_.isEmpty()) {
            if (conversBuilder_.isEmpty()) {
              conversBuilder_.dispose();
              conversBuilder_ = null;
              convers_ = other.convers_;
              bitField0_ = (bitField0_ & ~0x00000002);
              conversBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getConversFieldBuilder() : null;
            } else {
              conversBuilder_.addAllMessages(other.convers_);
            }
          }
        }
        if (other.getSize() != 0) {
          setSize(other.getSize());
        }
        if (other.getCount() != 0) {
          setCount(other.getCount());
        }
        if (other.getPage() != 0) {
          setPage(other.getPage());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object weChatId_ = "";
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public java.lang.String getWeChatId() {
        java.lang.Object ref = weChatId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weChatId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatIdBytes() {
        java.lang.Object ref = weChatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weChatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder clearWeChatId() {
        
        weChatId_ = getDefaultInstance().getWeChatId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weChatId_ = value;
        onChanged();
        return this;
      }

      private java.util.List<Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage> convers_ =
        java.util.Collections.emptyList();
      private void ensureConversIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          convers_ = new java.util.ArrayList<Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage>(convers_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder> conversBuilder_;

      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public java.util.List<Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage> getConversList() {
        if (conversBuilder_ == null) {
          return java.util.Collections.unmodifiableList(convers_);
        } else {
          return conversBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public int getConversCount() {
        if (conversBuilder_ == null) {
          return convers_.size();
        } else {
          return conversBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage getConvers(int index) {
        if (conversBuilder_ == null) {
          return convers_.get(index);
        } else {
          return conversBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder setConvers(
          int index, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage value) {
        if (conversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConversIsMutable();
          convers_.set(index, value);
          onChanged();
        } else {
          conversBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder setConvers(
          int index, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder builderForValue) {
        if (conversBuilder_ == null) {
          ensureConversIsMutable();
          convers_.set(index, builderForValue.build());
          onChanged();
        } else {
          conversBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder addConvers(Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage value) {
        if (conversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConversIsMutable();
          convers_.add(value);
          onChanged();
        } else {
          conversBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder addConvers(
          int index, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage value) {
        if (conversBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureConversIsMutable();
          convers_.add(index, value);
          onChanged();
        } else {
          conversBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder addConvers(
          Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder builderForValue) {
        if (conversBuilder_ == null) {
          ensureConversIsMutable();
          convers_.add(builderForValue.build());
          onChanged();
        } else {
          conversBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder addConvers(
          int index, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder builderForValue) {
        if (conversBuilder_ == null) {
          ensureConversIsMutable();
          convers_.add(index, builderForValue.build());
          onChanged();
        } else {
          conversBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder addAllConvers(
          java.lang.Iterable<? extends Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage> values) {
        if (conversBuilder_ == null) {
          ensureConversIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, convers_);
          onChanged();
        } else {
          conversBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder clearConvers() {
        if (conversBuilder_ == null) {
          convers_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          conversBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Builder removeConvers(int index) {
        if (conversBuilder_ == null) {
          ensureConversIsMutable();
          convers_.remove(index);
          onChanged();
        } else {
          conversBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder getConversBuilder(
          int index) {
        return getConversFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder getConversOrBuilder(
          int index) {
        if (conversBuilder_ == null) {
          return convers_.get(index);  } else {
          return conversBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public java.util.List<? extends Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder> 
           getConversOrBuilderList() {
        if (conversBuilder_ != null) {
          return conversBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(convers_);
        }
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder addConversBuilder() {
        return getConversFieldBuilder().addBuilder(
            Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder addConversBuilder(
          int index) {
        return getConversFieldBuilder().addBuilder(
            index, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.getDefaultInstance());
      }
      /**
       * <code>repeated .Jubo.JuLiao.IM.Wx.Proto.ConversMessage Convers = 2;</code>
       */
      public java.util.List<Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder> 
           getConversBuilderList() {
        return getConversFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder> 
          getConversFieldBuilder() {
        if (conversBuilder_ == null) {
          conversBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessage.Builder, Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversMessageOrBuilder>(
                  convers_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          convers_ = null;
        }
        return conversBuilder_;
      }

      private int size_ ;
      /**
       * <code>int32 Size = 3;</code>
       */
      public int getSize() {
        return size_;
      }
      /**
       * <code>int32 Size = 3;</code>
       */
      public Builder setSize(int value) {
        
        size_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Size = 3;</code>
       */
      public Builder clearSize() {
        
        size_ = 0;
        onChanged();
        return this;
      }

      private int count_ ;
      /**
       * <code>int32 Count = 4;</code>
       */
      public int getCount() {
        return count_;
      }
      /**
       * <code>int32 Count = 4;</code>
       */
      public Builder setCount(int value) {
        
        count_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Count = 4;</code>
       */
      public Builder clearCount() {
        
        count_ = 0;
        onChanged();
        return this;
      }

      private int page_ ;
      /**
       * <code>int32 Page = 5;</code>
       */
      public int getPage() {
        return page_;
      }
      /**
       * <code>int32 Page = 5;</code>
       */
      public Builder setPage(int value) {
        
        page_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 Page = 5;</code>
       */
      public Builder clearPage() {
        
        page_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.ConversationPushNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.ConversationPushNoticeMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ConversationPushNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<ConversationPushNoticeMessage>() {
      public ConversationPushNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ConversationPushNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ConversationPushNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ConversationPushNoticeMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.ConversationPushNotice.ConversationPushNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034ConversationPushNotice.proto\022\027Jubo.JuL" +
      "iao.IM.Wx.Proto\"\215\001\n\016ConversMessage\022\020\n\010Us" +
      "erName\030\001 \001(\t\022\016\n\006Digest\030\002 \001(\t\022\022\n\nDigestUs" +
      "er\030\003 \001(\t\022\016\n\006IsSend\030\004 \001(\010\022\016\n\006MsgCnt\030\005 \001(\005" +
      "\022\021\n\tUnreadCnt\030\006 \001(\005\022\022\n\nUpdateTime\030\007 \001(\003\"" +
      "\226\001\n\035ConversationPushNoticeMessage\022\020\n\010WeC" +
      "hatId\030\001 \001(\t\0228\n\007Convers\030\002 \003(\0132\'.Jubo.JuLi" +
      "ao.IM.Wx.Proto.ConversMessage\022\014\n\004Size\030\003 " +
      "\001(\005\022\r\n\005Count\030\004 \001(\005\022\014\n\004Page\030\005 \001(\005b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversMessage_descriptor,
        new java.lang.String[] { "UserName", "Digest", "DigestUser", "IsSend", "MsgCnt", "UnreadCnt", "UpdateTime", });
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_ConversationPushNoticeMessage_descriptor,
        new java.lang.String[] { "WeChatId", "Convers", "Size", "Count", "Page", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
