// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FindContactTaskResultNotice.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class FindContactTaskResultNotice {
  private FindContactTaskResultNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface FindContactTaskResultNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 商家所属微信号
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    java.lang.String getWeChatId();
    /**
     * <pre>
     * 商家所属微信号
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    com.google.protobuf.ByteString
        getWeChatIdBytes();

    /**
     * <pre>
     * 搜索的内容
     * </pre>
     *
     * <code>string SearchText = 2;</code>
     */
    java.lang.String getSearchText();
    /**
     * <pre>
     * 搜索的内容
     * </pre>
     *
     * <code>string SearchText = 2;</code>
     */
    com.google.protobuf.ByteString
        getSearchTextBytes();

    /**
     * <code>bool Success = 3;</code>
     */
    boolean getSuccess();

    /**
     * <code>bool IsFriend = 4;</code>
     */
    boolean getIsFriend();

    /**
     * <pre>
     * 微信id（不一定准确）
     * </pre>
     *
     * <code>string UserName = 5;</code>
     */
    java.lang.String getUserName();
    /**
     * <pre>
     * 微信id（不一定准确）
     * </pre>
     *
     * <code>string UserName = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <pre>
     * 微信号
     * </pre>
     *
     * <code>string Alias = 6;</code>
     */
    java.lang.String getAlias();
    /**
     * <pre>
     * 微信号
     * </pre>
     *
     * <code>string Alias = 6;</code>
     */
    com.google.protobuf.ByteString
        getAliasBytes();

    /**
     * <pre>
     * 微信昵称
     * </pre>
     *
     * <code>string NickName = 7;</code>
     */
    java.lang.String getNickName();
    /**
     * <pre>
     * 微信昵称
     * </pre>
     *
     * <code>string NickName = 7;</code>
     */
    com.google.protobuf.ByteString
        getNickNameBytes();

    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
     */
    int getGenderValue();
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
     */
    Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender getGender();

    /**
     * <pre>
     *国家 (非必传)
     * </pre>
     *
     * <code>string Country = 9;</code>
     */
    java.lang.String getCountry();
    /**
     * <pre>
     *国家 (非必传)
     * </pre>
     *
     * <code>string Country = 9;</code>
     */
    com.google.protobuf.ByteString
        getCountryBytes();

    /**
     * <pre>
     *省份
     * </pre>
     *
     * <code>string Province = 10;</code>
     */
    java.lang.String getProvince();
    /**
     * <pre>
     *省份
     * </pre>
     *
     * <code>string Province = 10;</code>
     */
    com.google.protobuf.ByteString
        getProvinceBytes();

    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>string City = 11;</code>
     */
    java.lang.String getCity();
    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>string City = 11;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <pre>
     *微信头像 
     * </pre>
     *
     * <code>string Avatar = 12;</code>
     */
    java.lang.String getAvatar();
    /**
     * <pre>
     *微信头像 
     * </pre>
     *
     * <code>string Avatar = 12;</code>
     */
    com.google.protobuf.ByteString
        getAvatarBytes();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNoticeMessage}
   */
  public  static final class FindContactTaskResultNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNoticeMessage)
      FindContactTaskResultNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use FindContactTaskResultNoticeMessage.newBuilder() to construct.
    private FindContactTaskResultNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FindContactTaskResultNoticeMessage() {
      weChatId_ = "";
      searchText_ = "";
      success_ = false;
      isFriend_ = false;
      userName_ = "";
      alias_ = "";
      nickName_ = "";
      gender_ = 0;
      country_ = "";
      province_ = "";
      city_ = "";
      avatar_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private FindContactTaskResultNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              weChatId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              searchText_ = s;
              break;
            }
            case 24: {

              success_ = input.readBool();
              break;
            }
            case 32: {

              isFriend_ = input.readBool();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              alias_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              nickName_ = s;
              break;
            }
            case 64: {
              int rawValue = input.readEnum();

              gender_ = rawValue;
              break;
            }
            case 74: {
              java.lang.String s = input.readStringRequireUtf8();

              country_ = s;
              break;
            }
            case 82: {
              java.lang.String s = input.readStringRequireUtf8();

              province_ = s;
              break;
            }
            case 90: {
              java.lang.String s = input.readStringRequireUtf8();

              city_ = s;
              break;
            }
            case 98: {
              java.lang.String s = input.readStringRequireUtf8();

              avatar_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage.Builder.class);
    }

    public static final int WECHATID_FIELD_NUMBER = 1;
    private volatile java.lang.Object weChatId_;
    /**
     * <pre>
     * 商家所属微信号
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public java.lang.String getWeChatId() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weChatId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 商家所属微信号
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatIdBytes() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weChatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SEARCHTEXT_FIELD_NUMBER = 2;
    private volatile java.lang.Object searchText_;
    /**
     * <pre>
     * 搜索的内容
     * </pre>
     *
     * <code>string SearchText = 2;</code>
     */
    public java.lang.String getSearchText() {
      java.lang.Object ref = searchText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        searchText_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 搜索的内容
     * </pre>
     *
     * <code>string SearchText = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSearchTextBytes() {
      java.lang.Object ref = searchText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        searchText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCCESS_FIELD_NUMBER = 3;
    private boolean success_;
    /**
     * <code>bool Success = 3;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int ISFRIEND_FIELD_NUMBER = 4;
    private boolean isFriend_;
    /**
     * <code>bool IsFriend = 4;</code>
     */
    public boolean getIsFriend() {
      return isFriend_;
    }

    public static final int USERNAME_FIELD_NUMBER = 5;
    private volatile java.lang.Object userName_;
    /**
     * <pre>
     * 微信id（不一定准确）
     * </pre>
     *
     * <code>string UserName = 5;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 微信id（不一定准确）
     * </pre>
     *
     * <code>string UserName = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ALIAS_FIELD_NUMBER = 6;
    private volatile java.lang.Object alias_;
    /**
     * <pre>
     * 微信号
     * </pre>
     *
     * <code>string Alias = 6;</code>
     */
    public java.lang.String getAlias() {
      java.lang.Object ref = alias_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        alias_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 微信号
     * </pre>
     *
     * <code>string Alias = 6;</code>
     */
    public com.google.protobuf.ByteString
        getAliasBytes() {
      java.lang.Object ref = alias_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        alias_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NICKNAME_FIELD_NUMBER = 7;
    private volatile java.lang.Object nickName_;
    /**
     * <pre>
     * 微信昵称
     * </pre>
     *
     * <code>string NickName = 7;</code>
     */
    public java.lang.String getNickName() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nickName_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 微信昵称
     * </pre>
     *
     * <code>string NickName = 7;</code>
     */
    public com.google.protobuf.ByteString
        getNickNameBytes() {
      java.lang.Object ref = nickName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nickName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int GENDER_FIELD_NUMBER = 8;
    private int gender_;
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
     */
    public int getGenderValue() {
      return gender_;
    }
    /**
     * <pre>
     *性别
     * </pre>
     *
     * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
     */
    public Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender getGender() {
      Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender result = Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender.valueOf(gender_);
      return result == null ? Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender.UNRECOGNIZED : result;
    }

    public static final int COUNTRY_FIELD_NUMBER = 9;
    private volatile java.lang.Object country_;
    /**
     * <pre>
     *国家 (非必传)
     * </pre>
     *
     * <code>string Country = 9;</code>
     */
    public java.lang.String getCountry() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        country_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *国家 (非必传)
     * </pre>
     *
     * <code>string Country = 9;</code>
     */
    public com.google.protobuf.ByteString
        getCountryBytes() {
      java.lang.Object ref = country_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        country_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PROVINCE_FIELD_NUMBER = 10;
    private volatile java.lang.Object province_;
    /**
     * <pre>
     *省份
     * </pre>
     *
     * <code>string Province = 10;</code>
     */
    public java.lang.String getProvince() {
      java.lang.Object ref = province_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        province_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *省份
     * </pre>
     *
     * <code>string Province = 10;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      java.lang.Object ref = province_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 11;
    private volatile java.lang.Object city_;
    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>string City = 11;</code>
     */
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *城市
     * </pre>
     *
     * <code>string City = 11;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int AVATAR_FIELD_NUMBER = 12;
    private volatile java.lang.Object avatar_;
    /**
     * <pre>
     *微信头像 
     * </pre>
     *
     * <code>string Avatar = 12;</code>
     */
    public java.lang.String getAvatar() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        avatar_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *微信头像 
     * </pre>
     *
     * <code>string Avatar = 12;</code>
     */
    public com.google.protobuf.ByteString
        getAvatarBytes() {
      java.lang.Object ref = avatar_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        avatar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWeChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, weChatId_);
      }
      if (!getSearchTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, searchText_);
      }
      if (success_ != false) {
        output.writeBool(3, success_);
      }
      if (isFriend_ != false) {
        output.writeBool(4, isFriend_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userName_);
      }
      if (!getAliasBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, alias_);
      }
      if (!getNickNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, nickName_);
      }
      if (gender_ != Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender.UnknownGender.getNumber()) {
        output.writeEnum(8, gender_);
      }
      if (!getCountryBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, country_);
      }
      if (!getProvinceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 10, province_);
      }
      if (!getCityBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 11, city_);
      }
      if (!getAvatarBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 12, avatar_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWeChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, weChatId_);
      }
      if (!getSearchTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, searchText_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, success_);
      }
      if (isFriend_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(4, isFriend_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userName_);
      }
      if (!getAliasBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, alias_);
      }
      if (!getNickNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, nickName_);
      }
      if (gender_ != Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender.UnknownGender.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(8, gender_);
      }
      if (!getCountryBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, country_);
      }
      if (!getProvinceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(10, province_);
      }
      if (!getCityBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(11, city_);
      }
      if (!getAvatarBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, avatar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage other = (Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage) obj;

      boolean result = true;
      result = result && getWeChatId()
          .equals(other.getWeChatId());
      result = result && getSearchText()
          .equals(other.getSearchText());
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && (getIsFriend()
          == other.getIsFriend());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getAlias()
          .equals(other.getAlias());
      result = result && getNickName()
          .equals(other.getNickName());
      result = result && gender_ == other.gender_;
      result = result && getCountry()
          .equals(other.getCountry());
      result = result && getProvince()
          .equals(other.getProvince());
      result = result && getCity()
          .equals(other.getCity());
      result = result && getAvatar()
          .equals(other.getAvatar());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WECHATID_FIELD_NUMBER;
      hash = (53 * hash) + getWeChatId().hashCode();
      hash = (37 * hash) + SEARCHTEXT_FIELD_NUMBER;
      hash = (53 * hash) + getSearchText().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + ISFRIEND_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getIsFriend());
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + ALIAS_FIELD_NUMBER;
      hash = (53 * hash) + getAlias().hashCode();
      hash = (37 * hash) + NICKNAME_FIELD_NUMBER;
      hash = (53 * hash) + getNickName().hashCode();
      hash = (37 * hash) + GENDER_FIELD_NUMBER;
      hash = (53 * hash) + gender_;
      hash = (37 * hash) + COUNTRY_FIELD_NUMBER;
      hash = (53 * hash) + getCountry().hashCode();
      hash = (37 * hash) + PROVINCE_FIELD_NUMBER;
      hash = (53 * hash) + getProvince().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + AVATAR_FIELD_NUMBER;
      hash = (53 * hash) + getAvatar().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNoticeMessage)
        Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        weChatId_ = "";

        searchText_ = "";

        success_ = false;

        isFriend_ = false;

        userName_ = "";

        alias_ = "";

        nickName_ = "";

        gender_ = 0;

        country_ = "";

        province_ = "";

        city_ = "";

        avatar_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage result = new Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage(this);
        result.weChatId_ = weChatId_;
        result.searchText_ = searchText_;
        result.success_ = success_;
        result.isFriend_ = isFriend_;
        result.userName_ = userName_;
        result.alias_ = alias_;
        result.nickName_ = nickName_;
        result.gender_ = gender_;
        result.country_ = country_;
        result.province_ = province_;
        result.city_ = city_;
        result.avatar_ = avatar_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage.getDefaultInstance()) return this;
        if (!other.getWeChatId().isEmpty()) {
          weChatId_ = other.weChatId_;
          onChanged();
        }
        if (!other.getSearchText().isEmpty()) {
          searchText_ = other.searchText_;
          onChanged();
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getIsFriend() != false) {
          setIsFriend(other.getIsFriend());
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getAlias().isEmpty()) {
          alias_ = other.alias_;
          onChanged();
        }
        if (!other.getNickName().isEmpty()) {
          nickName_ = other.nickName_;
          onChanged();
        }
        if (other.gender_ != 0) {
          setGenderValue(other.getGenderValue());
        }
        if (!other.getCountry().isEmpty()) {
          country_ = other.country_;
          onChanged();
        }
        if (!other.getProvince().isEmpty()) {
          province_ = other.province_;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          onChanged();
        }
        if (!other.getAvatar().isEmpty()) {
          avatar_ = other.avatar_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object weChatId_ = "";
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public java.lang.String getWeChatId() {
        java.lang.Object ref = weChatId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weChatId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatIdBytes() {
        java.lang.Object ref = weChatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weChatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder clearWeChatId() {
        
        weChatId_ = getDefaultInstance().getWeChatId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家所属微信号
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weChatId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object searchText_ = "";
      /**
       * <pre>
       * 搜索的内容
       * </pre>
       *
       * <code>string SearchText = 2;</code>
       */
      public java.lang.String getSearchText() {
        java.lang.Object ref = searchText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          searchText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 搜索的内容
       * </pre>
       *
       * <code>string SearchText = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSearchTextBytes() {
        java.lang.Object ref = searchText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          searchText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 搜索的内容
       * </pre>
       *
       * <code>string SearchText = 2;</code>
       */
      public Builder setSearchText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        searchText_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索的内容
       * </pre>
       *
       * <code>string SearchText = 2;</code>
       */
      public Builder clearSearchText() {
        
        searchText_ = getDefaultInstance().getSearchText();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 搜索的内容
       * </pre>
       *
       * <code>string SearchText = 2;</code>
       */
      public Builder setSearchTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        searchText_ = value;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <code>bool Success = 3;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <code>bool Success = 3;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool Success = 3;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private boolean isFriend_ ;
      /**
       * <code>bool IsFriend = 4;</code>
       */
      public boolean getIsFriend() {
        return isFriend_;
      }
      /**
       * <code>bool IsFriend = 4;</code>
       */
      public Builder setIsFriend(boolean value) {
        
        isFriend_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool IsFriend = 4;</code>
       */
      public Builder clearIsFriend() {
        
        isFriend_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <pre>
       * 微信id（不一定准确）
       * </pre>
       *
       * <code>string UserName = 5;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 微信id（不一定准确）
       * </pre>
       *
       * <code>string UserName = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 微信id（不一定准确）
       * </pre>
       *
       * <code>string UserName = 5;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 微信id（不一定准确）
       * </pre>
       *
       * <code>string UserName = 5;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 微信id（不一定准确）
       * </pre>
       *
       * <code>string UserName = 5;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object alias_ = "";
      /**
       * <pre>
       * 微信号
       * </pre>
       *
       * <code>string Alias = 6;</code>
       */
      public java.lang.String getAlias() {
        java.lang.Object ref = alias_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          alias_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 微信号
       * </pre>
       *
       * <code>string Alias = 6;</code>
       */
      public com.google.protobuf.ByteString
          getAliasBytes() {
        java.lang.Object ref = alias_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          alias_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 微信号
       * </pre>
       *
       * <code>string Alias = 6;</code>
       */
      public Builder setAlias(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        alias_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 微信号
       * </pre>
       *
       * <code>string Alias = 6;</code>
       */
      public Builder clearAlias() {
        
        alias_ = getDefaultInstance().getAlias();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 微信号
       * </pre>
       *
       * <code>string Alias = 6;</code>
       */
      public Builder setAliasBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        alias_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object nickName_ = "";
      /**
       * <pre>
       * 微信昵称
       * </pre>
       *
       * <code>string NickName = 7;</code>
       */
      public java.lang.String getNickName() {
        java.lang.Object ref = nickName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nickName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 微信昵称
       * </pre>
       *
       * <code>string NickName = 7;</code>
       */
      public com.google.protobuf.ByteString
          getNickNameBytes() {
        java.lang.Object ref = nickName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nickName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 微信昵称
       * </pre>
       *
       * <code>string NickName = 7;</code>
       */
      public Builder setNickName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nickName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 微信昵称
       * </pre>
       *
       * <code>string NickName = 7;</code>
       */
      public Builder clearNickName() {
        
        nickName_ = getDefaultInstance().getNickName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 微信昵称
       * </pre>
       *
       * <code>string NickName = 7;</code>
       */
      public Builder setNickNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nickName_ = value;
        onChanged();
        return this;
      }

      private int gender_ = 0;
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
       */
      public int getGenderValue() {
        return gender_;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
       */
      public Builder setGenderValue(int value) {
        gender_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
       */
      public Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender getGender() {
        Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender result = Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender.valueOf(gender_);
        return result == null ? Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
       */
      public Builder setGender(Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.EnumGender value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        gender_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *性别
       * </pre>
       *
       * <code>.Jubo.JuLiao.IM.Wx.Proto.EnumGender Gender = 8;</code>
       */
      public Builder clearGender() {
        
        gender_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object country_ = "";
      /**
       * <pre>
       *国家 (非必传)
       * </pre>
       *
       * <code>string Country = 9;</code>
       */
      public java.lang.String getCountry() {
        java.lang.Object ref = country_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          country_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *国家 (非必传)
       * </pre>
       *
       * <code>string Country = 9;</code>
       */
      public com.google.protobuf.ByteString
          getCountryBytes() {
        java.lang.Object ref = country_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          country_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *国家 (非必传)
       * </pre>
       *
       * <code>string Country = 9;</code>
       */
      public Builder setCountry(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        country_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *国家 (非必传)
       * </pre>
       *
       * <code>string Country = 9;</code>
       */
      public Builder clearCountry() {
        
        country_ = getDefaultInstance().getCountry();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *国家 (非必传)
       * </pre>
       *
       * <code>string Country = 9;</code>
       */
      public Builder setCountryBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        country_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object province_ = "";
      /**
       * <pre>
       *省份
       * </pre>
       *
       * <code>string Province = 10;</code>
       */
      public java.lang.String getProvince() {
        java.lang.Object ref = province_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          province_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *省份
       * </pre>
       *
       * <code>string Province = 10;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        java.lang.Object ref = province_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          province_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *省份
       * </pre>
       *
       * <code>string Province = 10;</code>
       */
      public Builder setProvince(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        province_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *省份
       * </pre>
       *
       * <code>string Province = 10;</code>
       */
      public Builder clearProvince() {
        
        province_ = getDefaultInstance().getProvince();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *省份
       * </pre>
       *
       * <code>string Province = 10;</code>
       */
      public Builder setProvinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        province_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>string City = 11;</code>
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>string City = 11;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>string City = 11;</code>
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>string City = 11;</code>
       */
      public Builder clearCity() {
        
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *城市
       * </pre>
       *
       * <code>string City = 11;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        city_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object avatar_ = "";
      /**
       * <pre>
       *微信头像 
       * </pre>
       *
       * <code>string Avatar = 12;</code>
       */
      public java.lang.String getAvatar() {
        java.lang.Object ref = avatar_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          avatar_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *微信头像 
       * </pre>
       *
       * <code>string Avatar = 12;</code>
       */
      public com.google.protobuf.ByteString
          getAvatarBytes() {
        java.lang.Object ref = avatar_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          avatar_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *微信头像 
       * </pre>
       *
       * <code>string Avatar = 12;</code>
       */
      public Builder setAvatar(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        avatar_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *微信头像 
       * </pre>
       *
       * <code>string Avatar = 12;</code>
       */
      public Builder clearAvatar() {
        
        avatar_ = getDefaultInstance().getAvatar();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *微信头像 
       * </pre>
       *
       * <code>string Avatar = 12;</code>
       */
      public Builder setAvatarBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        avatar_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNoticeMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FindContactTaskResultNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<FindContactTaskResultNoticeMessage>() {
      public FindContactTaskResultNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new FindContactTaskResultNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FindContactTaskResultNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FindContactTaskResultNoticeMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.FindContactTaskResultNotice.FindContactTaskResultNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!FindContactTaskResultNotice.proto\022\027Jub" +
      "o.JuLiao.IM.Wx.Proto\032\026TransportMessage.p" +
      "roto\"\226\002\n\"FindContactTaskResultNoticeMess" +
      "age\022\020\n\010WeChatId\030\001 \001(\t\022\022\n\nSearchText\030\002 \001(" +
      "\t\022\017\n\007Success\030\003 \001(\010\022\020\n\010IsFriend\030\004 \001(\010\022\020\n\010" +
      "UserName\030\005 \001(\t\022\r\n\005Alias\030\006 \001(\t\022\020\n\010NickNam" +
      "e\030\007 \001(\t\0223\n\006Gender\030\010 \001(\0162#.Jubo.JuLiao.IM" +
      ".Wx.Proto.EnumGender\022\017\n\007Country\030\t \001(\t\022\020\n" +
      "\010Province\030\n \001(\t\022\014\n\004City\030\013 \001(\t\022\016\n\006Avatar\030" +
      "\014 \001(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.getDescriptor(),
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_FindContactTaskResultNoticeMessage_descriptor,
        new java.lang.String[] { "WeChatId", "SearchText", "Success", "IsFriend", "UserName", "Alias", "NickName", "Gender", "Country", "Province", "City", "Avatar", });
    Jubo.JuLiao.IM.Wx.Proto.TransportMessageOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
