// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeChatLoginNoticeResp.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class WeChatLoginNoticeResp {
  private WeChatLoginNoticeResp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WeChatLoginNoticeRespMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeRespMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 已登录的wxid
     * </pre>
     *
     * <code>repeated string WeChats = 1;</code>
     */
    java.util.List<java.lang.String>
        getWeChatsList();
    /**
     * <pre>
     * 已登录的wxid
     * </pre>
     *
     * <code>repeated string WeChats = 1;</code>
     */
    int getWeChatsCount();
    /**
     * <pre>
     * 已登录的wxid
     * </pre>
     *
     * <code>repeated string WeChats = 1;</code>
     */
    java.lang.String getWeChats(int index);
    /**
     * <pre>
     * 已登录的wxid
     * </pre>
     *
     * <code>repeated string WeChats = 1;</code>
     */
    com.google.protobuf.ByteString
        getWeChatsBytes(int index);
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeRespMessage}
   */
  public  static final class WeChatLoginNoticeRespMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeRespMessage)
      WeChatLoginNoticeRespMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WeChatLoginNoticeRespMessage.newBuilder() to construct.
    private WeChatLoginNoticeRespMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WeChatLoginNoticeRespMessage() {
      weChats_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WeChatLoginNoticeRespMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                weChats_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              weChats_.add(s);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          weChats_ = weChats_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage.class, Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage.Builder.class);
    }

    public static final int WECHATS_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList weChats_;
    /**
     * <pre>
     * 已登录的wxid
     * </pre>
     *
     * <code>repeated string WeChats = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getWeChatsList() {
      return weChats_;
    }
    /**
     * <pre>
     * 已登录的wxid
     * </pre>
     *
     * <code>repeated string WeChats = 1;</code>
     */
    public int getWeChatsCount() {
      return weChats_.size();
    }
    /**
     * <pre>
     * 已登录的wxid
     * </pre>
     *
     * <code>repeated string WeChats = 1;</code>
     */
    public java.lang.String getWeChats(int index) {
      return weChats_.get(index);
    }
    /**
     * <pre>
     * 已登录的wxid
     * </pre>
     *
     * <code>repeated string WeChats = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatsBytes(int index) {
      return weChats_.getByteString(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < weChats_.size(); i++) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, weChats_.getRaw(i));
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < weChats_.size(); i++) {
          dataSize += computeStringSizeNoTag(weChats_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getWeChatsList().size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage other = (Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage) obj;

      boolean result = true;
      result = result && getWeChatsList()
          .equals(other.getWeChatsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getWeChatsCount() > 0) {
        hash = (37 * hash) + WECHATS_FIELD_NUMBER;
        hash = (53 * hash) + getWeChatsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeRespMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeRespMessage)
        Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage.class, Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        weChats_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage result = new Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          weChats_ = weChats_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.weChats_ = weChats_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage.getDefaultInstance()) return this;
        if (!other.weChats_.isEmpty()) {
          if (weChats_.isEmpty()) {
            weChats_ = other.weChats_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureWeChatsIsMutable();
            weChats_.addAll(other.weChats_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList weChats_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureWeChatsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          weChats_ = new com.google.protobuf.LazyStringArrayList(weChats_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getWeChatsList() {
        return weChats_.getUnmodifiableView();
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public int getWeChatsCount() {
        return weChats_.size();
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public java.lang.String getWeChats(int index) {
        return weChats_.get(index);
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatsBytes(int index) {
        return weChats_.getByteString(index);
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public Builder setWeChats(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWeChatsIsMutable();
        weChats_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public Builder addWeChats(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureWeChatsIsMutable();
        weChats_.add(value);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public Builder addAllWeChats(
          java.lang.Iterable<java.lang.String> values) {
        ensureWeChatsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, weChats_);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public Builder clearWeChats() {
        weChats_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 已登录的wxid
       * </pre>
       *
       * <code>repeated string WeChats = 1;</code>
       */
      public Builder addWeChatsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        ensureWeChatsIsMutable();
        weChats_.add(value);
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeRespMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeRespMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WeChatLoginNoticeRespMessage>
        PARSER = new com.google.protobuf.AbstractParser<WeChatLoginNoticeRespMessage>() {
      public WeChatLoginNoticeRespMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeChatLoginNoticeRespMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WeChatLoginNoticeRespMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WeChatLoginNoticeRespMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.WeChatLoginNoticeResp.WeChatLoginNoticeRespMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\033WeChatLoginNoticeResp.proto\022\027Jubo.JuLi" +
      "ao.IM.Wx.Proto\"/\n\034WeChatLoginNoticeRespM" +
      "essage\022\017\n\007WeChats\030\001 \003(\tb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLoginNoticeRespMessage_descriptor,
        new java.lang.String[] { "WeChats", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
