// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WeChatLocationTaskResultNotice.proto

package Jubo.JuLiao.IM.Wx.Proto;

public final class WeChatLocationTaskResultNotice {
  private WeChatLocationTaskResultNotice() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface WeChatLocationTaskResultNoticeMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNoticeMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    java.lang.String getWeChatId();
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    com.google.protobuf.ByteString
        getWeChatIdBytes();

    /**
     * <code>string IMEI = 2;</code>
     */
    java.lang.String getIMEI();
    /**
     * <code>string IMEI = 2;</code>
     */
    com.google.protobuf.ByteString
        getIMEIBytes();

    /**
     * <pre>
     * 是否成功
     * </pre>
     *
     * <code>bool Success = 3;</code>
     */
    boolean getSuccess();

    /**
     * <pre>
     * 经度
     * </pre>
     *
     * <code>float Lng = 4;</code>
     */
    float getLng();

    /**
     * <pre>
     * 纬度
     * </pre>
     *
     * <code>float Lat = 5;</code>
     */
    float getLat();
  }
  /**
   * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNoticeMessage}
   */
  public  static final class WeChatLocationTaskResultNoticeMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNoticeMessage)
      WeChatLocationTaskResultNoticeMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WeChatLocationTaskResultNoticeMessage.newBuilder() to construct.
    private WeChatLocationTaskResultNoticeMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WeChatLocationTaskResultNoticeMessage() {
      weChatId_ = "";
      iMEI_ = "";
      success_ = false;
      lng_ = 0F;
      lat_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private WeChatLocationTaskResultNoticeMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              weChatId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              iMEI_ = s;
              break;
            }
            case 24: {

              success_ = input.readBool();
              break;
            }
            case 37: {

              lng_ = input.readFloat();
              break;
            }
            case 45: {

              lat_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage.Builder.class);
    }

    public static final int WECHATID_FIELD_NUMBER = 1;
    private volatile java.lang.Object weChatId_;
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public java.lang.String getWeChatId() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        weChatId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * 商家个人微信内部全局唯一识别码
     * </pre>
     *
     * <code>string WeChatId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getWeChatIdBytes() {
      java.lang.Object ref = weChatId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        weChatId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMEI_FIELD_NUMBER = 2;
    private volatile java.lang.Object iMEI_;
    /**
     * <code>string IMEI = 2;</code>
     */
    public java.lang.String getIMEI() {
      java.lang.Object ref = iMEI_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        iMEI_ = s;
        return s;
      }
    }
    /**
     * <code>string IMEI = 2;</code>
     */
    public com.google.protobuf.ByteString
        getIMEIBytes() {
      java.lang.Object ref = iMEI_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        iMEI_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SUCCESS_FIELD_NUMBER = 3;
    private boolean success_;
    /**
     * <pre>
     * 是否成功
     * </pre>
     *
     * <code>bool Success = 3;</code>
     */
    public boolean getSuccess() {
      return success_;
    }

    public static final int LNG_FIELD_NUMBER = 4;
    private float lng_;
    /**
     * <pre>
     * 经度
     * </pre>
     *
     * <code>float Lng = 4;</code>
     */
    public float getLng() {
      return lng_;
    }

    public static final int LAT_FIELD_NUMBER = 5;
    private float lat_;
    /**
     * <pre>
     * 纬度
     * </pre>
     *
     * <code>float Lat = 5;</code>
     */
    public float getLat() {
      return lat_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getWeChatIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, weChatId_);
      }
      if (!getIMEIBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iMEI_);
      }
      if (success_ != false) {
        output.writeBool(3, success_);
      }
      if (lng_ != 0F) {
        output.writeFloat(4, lng_);
      }
      if (lat_ != 0F) {
        output.writeFloat(5, lat_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getWeChatIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, weChatId_);
      }
      if (!getIMEIBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iMEI_);
      }
      if (success_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, success_);
      }
      if (lng_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, lng_);
      }
      if (lat_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, lat_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage)) {
        return super.equals(obj);
      }
      Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage other = (Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage) obj;

      boolean result = true;
      result = result && getWeChatId()
          .equals(other.getWeChatId());
      result = result && getIMEI()
          .equals(other.getIMEI());
      result = result && (getSuccess()
          == other.getSuccess());
      result = result && (
          java.lang.Float.floatToIntBits(getLng())
          == java.lang.Float.floatToIntBits(
              other.getLng()));
      result = result && (
          java.lang.Float.floatToIntBits(getLat())
          == java.lang.Float.floatToIntBits(
              other.getLat()));
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WECHATID_FIELD_NUMBER;
      hash = (53 * hash) + getWeChatId().hashCode();
      hash = (37 * hash) + IMEI_FIELD_NUMBER;
      hash = (53 * hash) + getIMEI().hashCode();
      hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSuccess());
      hash = (37 * hash) + LNG_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLng());
      hash = (37 * hash) + LAT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getLat());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNoticeMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNoticeMessage)
        Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage.class, Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage.Builder.class);
      }

      // Construct using Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        weChatId_ = "";

        iMEI_ = "";

        success_ = false;

        lng_ = 0F;

        lat_ = 0F;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_descriptor;
      }

      public Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage getDefaultInstanceForType() {
        return Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage.getDefaultInstance();
      }

      public Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage build() {
        Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage buildPartial() {
        Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage result = new Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage(this);
        result.weChatId_ = weChatId_;
        result.iMEI_ = iMEI_;
        result.success_ = success_;
        result.lng_ = lng_;
        result.lat_ = lat_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage) {
          return mergeFrom((Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage other) {
        if (other == Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage.getDefaultInstance()) return this;
        if (!other.getWeChatId().isEmpty()) {
          weChatId_ = other.weChatId_;
          onChanged();
        }
        if (!other.getIMEI().isEmpty()) {
          iMEI_ = other.iMEI_;
          onChanged();
        }
        if (other.getSuccess() != false) {
          setSuccess(other.getSuccess());
        }
        if (other.getLng() != 0F) {
          setLng(other.getLng());
        }
        if (other.getLat() != 0F) {
          setLat(other.getLat());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object weChatId_ = "";
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public java.lang.String getWeChatId() {
        java.lang.Object ref = weChatId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          weChatId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getWeChatIdBytes() {
        java.lang.Object ref = weChatId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          weChatId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        weChatId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder clearWeChatId() {
        
        weChatId_ = getDefaultInstance().getWeChatId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 商家个人微信内部全局唯一识别码
       * </pre>
       *
       * <code>string WeChatId = 1;</code>
       */
      public Builder setWeChatIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        weChatId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object iMEI_ = "";
      /**
       * <code>string IMEI = 2;</code>
       */
      public java.lang.String getIMEI() {
        java.lang.Object ref = iMEI_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iMEI_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string IMEI = 2;</code>
       */
      public com.google.protobuf.ByteString
          getIMEIBytes() {
        java.lang.Object ref = iMEI_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iMEI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string IMEI = 2;</code>
       */
      public Builder setIMEI(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        iMEI_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string IMEI = 2;</code>
       */
      public Builder clearIMEI() {
        
        iMEI_ = getDefaultInstance().getIMEI();
        onChanged();
        return this;
      }
      /**
       * <code>string IMEI = 2;</code>
       */
      public Builder setIMEIBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        iMEI_ = value;
        onChanged();
        return this;
      }

      private boolean success_ ;
      /**
       * <pre>
       * 是否成功
       * </pre>
       *
       * <code>bool Success = 3;</code>
       */
      public boolean getSuccess() {
        return success_;
      }
      /**
       * <pre>
       * 是否成功
       * </pre>
       *
       * <code>bool Success = 3;</code>
       */
      public Builder setSuccess(boolean value) {
        
        success_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 是否成功
       * </pre>
       *
       * <code>bool Success = 3;</code>
       */
      public Builder clearSuccess() {
        
        success_ = false;
        onChanged();
        return this;
      }

      private float lng_ ;
      /**
       * <pre>
       * 经度
       * </pre>
       *
       * <code>float Lng = 4;</code>
       */
      public float getLng() {
        return lng_;
      }
      /**
       * <pre>
       * 经度
       * </pre>
       *
       * <code>float Lng = 4;</code>
       */
      public Builder setLng(float value) {
        
        lng_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 经度
       * </pre>
       *
       * <code>float Lng = 4;</code>
       */
      public Builder clearLng() {
        
        lng_ = 0F;
        onChanged();
        return this;
      }

      private float lat_ ;
      /**
       * <pre>
       * 纬度
       * </pre>
       *
       * <code>float Lat = 5;</code>
       */
      public float getLat() {
        return lat_;
      }
      /**
       * <pre>
       * 纬度
       * </pre>
       *
       * <code>float Lat = 5;</code>
       */
      public Builder setLat(float value) {
        
        lat_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 纬度
       * </pre>
       *
       * <code>float Lat = 5;</code>
       */
      public Builder clearLat() {
        
        lat_ = 0F;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNoticeMessage)
    }

    // @@protoc_insertion_point(class_scope:Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNoticeMessage)
    private static final Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage();
    }

    public static Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WeChatLocationTaskResultNoticeMessage>
        PARSER = new com.google.protobuf.AbstractParser<WeChatLocationTaskResultNoticeMessage>() {
      public WeChatLocationTaskResultNoticeMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new WeChatLocationTaskResultNoticeMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WeChatLocationTaskResultNoticeMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WeChatLocationTaskResultNoticeMessage> getParserForType() {
      return PARSER;
    }

    public Jubo.JuLiao.IM.Wx.Proto.WeChatLocationTaskResultNotice.WeChatLocationTaskResultNoticeMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$WeChatLocationTaskResultNotice.proto\022\027" +
      "Jubo.JuLiao.IM.Wx.Proto\"r\n%WeChatLocatio" +
      "nTaskResultNoticeMessage\022\020\n\010WeChatId\030\001 \001" +
      "(\t\022\014\n\004IMEI\030\002 \001(\t\022\017\n\007Success\030\003 \001(\010\022\013\n\003Lng" +
      "\030\004 \001(\002\022\013\n\003Lat\030\005 \001(\002b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Jubo_JuLiao_IM_Wx_Proto_WeChatLocationTaskResultNoticeMessage_descriptor,
        new java.lang.String[] { "WeChatId", "IMEI", "Success", "Lng", "Lat", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
